
name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2


      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false
